version = 1

[[analyzers]]
name = "csharp"
enabled = true

test_patterns = [
  "tests/**",
  "*Test.cs"
]

exclude_patterns = [
  "**/examples/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = [
    "react",
    "angularjs",
    "angular"
  ]
  environment = [
    "browser",
    "nodejs"
  ]
